import { normalizeMarkdown, toTitleCase } from "../text.js";
import type { InitInput, ProjectPlan } from "../types.js";
import { includesClaude, includesCodex } from "./shared.js";

export function buildReadme(input: InitInput, plan: ProjectPlan): string {
  const supportLines = [
    includesCodex(input.targetAgent) ? "- Codex CLI adapter: `AGENTS.md` + scoped `AGENTS.md` files." : null,
    includesClaude(input.targetAgent) ? "- Claude Code adapter: `CLAUDE.md` + `.claude/rules/`." : null,
    input.includeCursorRules ? "- Cursor adapter: `.cursor/rules/`." : null
  ]
    .filter(Boolean)
    .join("\n");

  return normalizeMarkdown(`# ${toTitleCase(input.projectName)}

${input.description}

## Generated By primer-ai
- Project shape: ${toTitleCase(input.projectShape)}
- Stack: ${input.techStack}
- Assistant workflow target: ${input.targetAgent}

## Knowledge Architecture
- Root routing: \`AGENTS.md\`
- Source of truth: \`docs/*\`
- Scoped instructions: nested \`AGENTS.md\` files per directory
- Root composition: \`.agents/fragments/root/*\` + \`node scripts/compose-agents.mjs --write\`
${supportLines}

## Quick Start
1. Install dependencies for your selected stack.
2. Run context maintenance checks:
   - \`node scripts/check-agent-context.mjs\`
   - \`node scripts/check-doc-freshness.mjs\`
   - \`node scripts/check-skills.mjs\`
3. Run stack verification commands:
${plan.verificationCommands.map((command) => `   - \`${command}\``).join("\n")}
4. Start local runtime with \`${plan.launchCommand}\`.

## Documentation
- \`docs/index.md\`
- \`docs/architecture.md\`
- \`docs/api-contracts.md\`
- \`docs/conventions.md\`
- \`docs/maintenance.md\`
- \`docs/skills.md\`
`);
}

export function buildScaffoldGitignore(): string {
  return normalizeMarkdown(`.DS_Store
node_modules/
dist/
coverage/
.env
.env.*
*.log
`);
}
