import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { FileArtifact } from "../../core/types.js";

const README_CONTEXT_START = "<!-- primer-ai:agent-context:start -->";
const README_CONTEXT_END = "<!-- primer-ai:agent-context:end -->";

function extractPrimerReadmeContext(generatedReadme: string): string {
  const lines = generatedReadme.trim().split("\n");
  const contextStart = lines.findIndex((line) => line.trim() === "## Generated By primer-ai");
  if (contextStart === -1) {
    return generatedReadme.trim();
  }
  return lines.slice(contextStart).join("\n").trim();
}

function buildPrimerReadmeBlock(generatedReadme: string): string {
  const context = extractPrimerReadmeContext(generatedReadme);
  return `${README_CONTEXT_START}
## AI Agent Context (Managed by primer-ai)

${context}
${README_CONTEXT_END}`;
}

function mergeReadmeContent(existingReadme: string, generatedReadme: string): string {
  const existingTrimmed = existingReadme.trim();
  if (!existingTrimmed) return generatedReadme;

  const block = buildPrimerReadmeBlock(generatedReadme);
  const startIndex = existingReadme.indexOf(README_CONTEXT_START);
  const endIndex = existingReadme.indexOf(README_CONTEXT_END);

  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const suffixStart = endIndex + README_CONTEXT_END.length;
    const merged =
      `${existingReadme.slice(0, startIndex).trimEnd()}\n\n${block}\n${existingReadme.slice(suffixStart).trimStart()}`;
    return `${merged.trimEnd()}\n`;
  }

  return `${existingReadme.trimEnd()}\n\n${block}\n`;
}

export function mergeReadmeArtifact(targetDir: string, files: FileArtifact[]): {
  files: FileArtifact[];
  merged: boolean;
} {
  const readmePath = join(targetDir, "README.md");
  if (!existsSync(readmePath)) {
    return { files, merged: false };
  }

  const index = files.findIndex((file) => file.path === "README.md");
  if (index === -1) {
    return { files, merged: false };
  }

  const existingReadme = readFileSync(readmePath, "utf8");
  const generatedReadme = files[index]?.content ?? "";
  const mergedReadme = mergeReadmeContent(existingReadme, generatedReadme);
  const nextFiles = files.slice();
  nextFiles[index] = {
    ...(nextFiles[index] as FileArtifact),
    path: "README.md",
    content: mergedReadme
  };

  return {
    files: nextFiles,
    merged: true
  };
}
